DELETE FROM tb_l_logger WHERE N_SEQ_NO = 1 AND V_APL_ID = '0124';
DELETE FROM tb_m_module_d WHERE V_FUNCTION_ID  = 'ST3402' AND V_MODULE_ID = 'ST30400';
DELETE FROM tb_m_module_h WHERE V_MODULE_ID = 'ST30400';

commit;