DELETE FROM TB_M_BATCH where BATCH_ID = 'BST33001' AND PROJECT_CODE = 'ST3';

DELETE FROM TB_R_BATCH_QUEUE where BATCH_ID = 'BST33001' AND PROJECT_CODE = 'ST3' AND APP_ID = 'TEST_Q_APP';

DELETE FROM TB_L_BATCH_STATUS_LOG where BATCH_ID = 'BST33001' AND PROJECT_CODE = 'ST3' AND APP_ID = 'TEST_L_APP';

DELETE FROM TB_M_SYSTEM where CATEGORY = 'BFW' AND SUB_CATEGORY = 'APP_LOG_URL' AND CD = 'ST3_BST33001';

commit;