INSERT INTO TB_M_BATCH (CREATE_BY, CREATE_DT, UPDATE_BY, UPDATE_DT, BATCH_NAME, CONCURRENCY_FLAG, PRIORITY_LEVEL, RUN_AS, RUNNING_COUNT, SHELL, SUPPORT_ID, BATCH_ID, PROJECT_CODE) 
values ('testuser', DATE '2015-06-17', 'testuser', DATE '2015-06-17', 'BATCH_NAME', '1', '1', 'test', 0, '', '', 'BST33001', 'ST3');

INSERT INTO TB_R_BATCH_QUEUE (APP_ID, BATCH_ID, DESCRIPTION, PARAMETERS, PROJECT_CODE, REQUEST_BY, REQUEST_DATE, REQUEST_ID, SUPPORT_ID, QUEUE_NO) 
values ('TEST_Q_APP', 'BST33001', '', '', 'ST3', 'testuser', DATE '2015-06-17', 'test', '', 101);

INSERT INTO TB_L_BATCH_STATUS_LOG (APP_ID, BATCH_ID, DESCRIPTION, MESSAGE, PARAMETERS, PROJECT_CODE, REQUEST_BY, REQUEST_ID, RUN_DATE, SUPPORT_ID, GROUP_SEQ_NO, SEQ_NO) 
values ('TEST_L_APP', 'BST33001', '', 'POSTED FOR WORK', '', 'ST3', 'testuser', 'test', DATE '2015-06-17', '', 1,102);

INSERT INTO TB_L_BATCH_STATUS_LOG (APP_ID, BATCH_ID, DESCRIPTION, MESSAGE, PARAMETERS, PROJECT_CODE, REQUEST_BY, REQUEST_ID, RUN_DATE, SUPPORT_ID, GROUP_SEQ_NO, SEQ_NO) 
values ('TEST_L_APP', 'BST33001', '', 'POSTED FOR WORK', '', 'ST3', 'testuser', 'test', DATE '2015-06-17', '', 1,103);

INSERT INTO TB_L_BATCH_STATUS_LOG (APP_ID, BATCH_ID, DESCRIPTION, MESSAGE, PARAMETERS, PROJECT_CODE, REQUEST_BY, REQUEST_ID, RUN_DATE, SUPPORT_ID, GROUP_SEQ_NO, SEQ_NO) 
values ('TEST_L_APP', 'BST33001', '', 'PROCESSING', '', 'ST3', 'testuser', 'test', DATE '2015-06-17', '', 2, 103);

INSERT INTO TB_M_SYSTEM (CATEGORY, SUB_CATEGORY, CD, VALUE, REMARK, STATUS, CREATE_BY, CREATE_DT, UPDATE_BY, UPDATE_DT)
values('BFW', 'APP_LOG_URL','ST3_BST33001', 'logmonterurl.com', 'remark', 'N', 'test', DATE '2015-06-17', 'test', DATE '2015-06-17');

commit;