INSERT INTO TB_M_BATCH (CREATE_BY, CREATE_DT, UPDATE_BY, UPDATE_DT, BATCH_NAME, CONCURRENCY_FLAG, PRIORITY_LEVEL, RUN_AS, RUNNING_COUNT, SHELL, SUPPORT_ID, BATCH_ID, PROJECT_CODE) 
values ('testuser', DATE '2015-06-17', 'testuser', DATE '2015-06-17', 'BATCH_NAME', '2', '1', 'test', 0, 'shell.sh', 'support', 'BST33001', 'ST3');

INSERT INTO TB_M_BATCH (CREATE_BY, CREATE_DT, UPDATE_BY, UPDATE_DT, BATCH_NAME, CONCURRENCY_FLAG, PRIORITY_LEVEL, RUN_AS, RUNNING_COUNT, SHELL, SUPPORT_ID, BATCH_ID, PROJECT_CODE) 
values ('testuser', DATE '2015-06-17' , 'testuser', DATE '2015-06-17', 'BATCH NAME TO TEST', '1', '1', 'test', 0, 'shell.sh', 'support', 'BST33000', 'ST3');

commit;